# Generated by Django 4.2 on 2023-05-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('operacao', models.CharField(max_length=100)),
                ('valor_bruto', models.CharField(max_length=100)),
                ('valor_liquido', models.CharField(max_length=100)),
                ('lancamento', models.CharField(max_length=100)),
                ('data_lancamento', models.CharField(max_length=100)),
                ('data_upload', models.CharField(max_length=100)),
            ],
        ),
    ]
