# Generated by Django 4.2 on 2023-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='cliente',
            new_name='banco',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='data_lancamento',
            new_name='bruto_contrato',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='data_upload',
            new_name='data_da_proposta',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='lancamento',
            new_name='data_do_lancamento',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='operacao',
            new_name='layout',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='proposta',
            new_name='liquido_contrato',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='valor_bruto',
            new_name='natureza_do_lancamento',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='valor_liquido',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='observacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvdata',
            name='percentual_lancamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvdata',
            name='tipo_de_lancamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csvdata',
            name='vlr_lancamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
