# Generated by Django 4.2 on 2023-05-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlapp', '0002_rename_cliente_csvdata_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvdata',
            name='proposta',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
